export type Page =
  | 'dashboard'
  | 'flows'
  | 'flowIntel'
  | 'bots'
  | 'users'
  | 'analytics'
  | 'webhooks'
  | 'payments'
  | 'paymentRadar'
  | 'remarketing'
  | 'mailing'
  | 'alerts'
  | 'account'
